### PR TITLE
fix: use explicit repeatOnLifecycle to fix android studio lint check

### PR DESCRIPTION
**Pull request by skyleaworlder**

### CODE REVIEW

**Comment by w568w** [comment]
What kind of warning do you get? 🤔 Everything's okay for me:
image

**Comment by skyleaworlder** [comment]
In fact, I also consider this problem is not common when I push this patch. I get this warning:

截屏2022-07-23 下午4 24 03

and I add "LifecycleOwner" as [this](https://stackoverflow.com/questions/71164314/android-studio-doesnt-let-me-use-repeatonlifecycle) told:

> The repeatOnLifecycle is an extension on a LifecycleOwner - here, you are implicitly using this - i.e., the Fragment's Lifeycle and most important not the Fragment View Lifecycle.

**Comment by w568w** [comment]
Strange to see that warning. It may be a false positive as one of the links referred in the Stackoverflow comments [says "this fix will be available in the Fragment 1.5.1 release"](https://issuetracker.google.com/issues/209658963#comment7) several days ago. 

I think you could, after all, mute the inspection as below:
image

It should not affect the application, since `LifecycleOwner.repeatOnLifecycle` is simply a shortcut for `Lifecycle.repeatOnLifecycle`. It does nothing special.

**Comment by skyleaworlder** [comment]
Thanks for your analysis, I see. I think it's okay to close this PR.

**Pull request closed without merging**
